the-marenga/sf-api

- .gitignore
- Cargo.toml
- README.md
- src/gamestate/arena.rs
- src/gamestate/character.rs
- src/gamestate/dungeons.rs
- src/gamestate/mod.rs
- src/gamestate/rewards.rs
- src/gamestate/social.rs
- src/gamestate/underworld.rs
Adds
- Other player portal bonuses
- Arena xp fight count
- More event (task) parsing
Fixes:
- Underworld next level u8 -> u16
- Make shop items public
> Several Fixes (v0.1.0)

- src/session.rs
- src/sso.rs
Adds SSO login through google and fixes an error in the parsing of server errors
> Google SSO

- src/command.rs
- src/session.rs
- src/sso.rs
- Increase HoF entries per page to 51
- Add a non-mut version of send_command to allow multithreaded use of session
- Minor updates on the Google & Steam auth stuff
> Multiple updates

- src/gamestate/character.rs
Turns out horns also have color
> Fix for horns

- src/gamestate/character.rs
Seems like special can be both negative and positive. I guess positive might be the frame and negative the influencer portrait?
> Special is annoying

- src/command.rs
- src/gamestate/dungeons.rs
- src/sso.rs
> Various fixes

- src/gamestate/items.rs
> Fix potion size

- src/gamestate/items.rs
- src/gamestate/rewards.rs
Can be useful when only wanting to check for a specific task that might be required for the day that might not be done after doing the daily routines e.g playing against the gambler or attacks without a weapon, then theres no need to filter the tasks Vec. Also formatting and clippy.
> Macro to check whether a task is required and not completed

- src/gamestate/unlockables.rs
> Should fix unlockable parsing

- src/gamestate/character.rs
- src/gamestate/mod.rs
Fixes: #91
Not my proudest PR, but I thought I might reduce your 5 button presses to 1 🥇
> Fix typo in Character struct

- src/gamestate/items.rs
- src/gamestate/rewards.rs
got annoyed with the warnings about unknown tasks so I fixed that
also fixed some typos I found :)
> add beginner quests and some convenience functions

- src/gamestate/rewards.rs
> fix stlye issues and required points for the final chest

- src/gamestate/mod.rs
no idea what they do but they seem very irrelevant and just spam the logs with warnings
> ignore some more irrelevant entries

- src/gamestate/rewards.rs
> add new Hellevator event task theme

- src/gamestate/rewards.rs
> Add missing event task themes

- src/command.rs
theoretically the parsing would be faster but I mostly did it because you no longer have to edit things at 2 places and can directly see the mapping
Also added the last missing countries I failed to add last time :^)
> use a macro to generate the flag enum and its conversion functions

- src/gamestate/guild.rs
seems like they changed that some time ago
the field also contains some other flags but I have no idea what they do or mean
> fix parsing of battles_joined

- src/gamestate/unlockables.rs
After spending an hour checking whether the parsing is incorrect i realised the order just isnt
> Pet order is incorrect

- src/simulate/mod.rs
> Change rage formula

- src/gamestate/mod.rs
When the underworld is unlocked Heart is on lvl 1 and honor is 0
> Underworld unlock check

- src/gamestate/mod.rs
Reverts the-marenga/sf-api#126
> Revert "Add function to check if a `DateTime` is in the future"

- README.md
- examples/decrypt_url.rs
- src/command.rs
- src/error.rs
- src/gamestate/arena.rs
- src/gamestate/fortress.rs
- src/gamestate/guild.rs
- src/gamestate/idle.rs
- src/gamestate/items.rs
- src/gamestate/mod.rs
- src/gamestate/rewards.rs
- src/gamestate/social.rs
- src/gamestate/tavern.rs
- src/gamestate/underworld.rs
- src/gamestate/unlockables.rs
- src/misc.rs
- src/response.rs
- src/session.rs
- src/sso.rs
In this pull request I cleaned up the texts in this project:
- Correctly abbreviated technical terms
- Fixed multiple typos and grammar mistakes
- Removed unnecessary consecutive spaces in comments
> Cleanup texts in this project

- src/gamestate/rewards.rs
Just some new tasks I've encountered
> add tasks 133 and 134

- src/gamestate/character.rs
- src/simulate/mod.rs
Make UpgradeableFighter actually useful and probably fix #116
> UpgradeableFighter updates

- src/gamestate/mod.rs
- src/gamestate/unlockables.rs
found that in the higher level (70+) are actually are some new reward types
> add some missing hellevator reward types

- src/gamestate/guild.rs
finally figured out what the lower 16 bits for portal are used for :)
> parse guild total skills

- src/gamestate/social.rs
- src/session.rs
> Added some Session functions to SimpleSession

- src/gamestate/mod.rs
- src/gamestate/social.rs
Forgot other player also has equipment
> Fixed equipment on otherplayer

- src/gamestate/tavern.rs
I found this useful for the 12th beer from weekly quests / other events.
> Total amount of beers you can drink 
