src/gamestate/unlockables.rs
Seems like the range for the legendary scout belts was too short
=> Possibly fix for missing scrapbook item

src/command.rs, src/gamestate/mod.rs, src/gamestate/rewards.rs, src/gamestate/social.rs, src/gamestate/unlockables.rs
- Handle >2 rewards
- Update the reward type parsing to the new standard
- Mail colelctables is the same as rewards now, so I merged them into just Rewards
- Added all event/daily task types
- Merged event&daily tasks now, that I know they are the same
- Also added the command to buy gold player frame
fixes #76 #48
=> Update (daily/event) parsing

src/gamestate/items.rs
Instead of just providing the index of a free slot it sometimes is necessary to know the amount of free slots available, for example when doing barehanded attacks for DailyTasks. Probably a very "hacky" solution..
=> Count the amount of free slots across MainInventory and ExtendedInventory

src/command.rs
Seems like I broke fortressfinish at some point. Prosumeable when I renamed a few things. Partially helps #85 
Also noticed that the underworldupgradecomplete command had an inconsistent name, so I changed that to the more used finish
=> Fortress & Underworld finish fixes

src/gamestate/tavern.rs
Some of the names in the API seemed outdated so I renamed them to their actual questnames. Makes it easier to follow what you are actually choosing.
=> updated names of expeditions

src/gamestate/mod.rs
this can for example happen when fetching the very last page of a server previously this would give warnings and now just stops parsing
example response for the last page:
```json
{"Ranklistplayer": "13006,ち丹メメメモ尺,,1,0,6,;13007,Julas4571,,1,0,4,;13008,VALERIA,,1,0,5,;13009,Mega,,1,0,10,;13010,Stacholski,,1,0,9,;13011,Navarro,,10,0,6,;13012,Geniowska,,1,0,1,;13013,cnnr,,1,0,4,;13014,Omel,,1,0,2,;13015,M4rbi,,14,0,3,;13016,Arxus,,1,0,3,;13017,Latmanen,,1,0,3,;13018,Dante Alighieri,,1,0,7,;13019,Sameubek Jurokis,,1,0,7,;13020,Hvbson,,10,0,2,;13021,Gigassassin,FridgeIndustries,26,0,4,;13022,vostra,,5,0,2,;13023,ViTrEx,,11,0,9,;13024,IceMage,,4,0,2,;13025,Gargulec12,,11,0,2,;13026,Kitty,,1,0,1,;13027,The Wall,,1,0,1,;13028,,,0,0,0,;13029,,,0,0,0,;13030,,,0,0,0,;13031,,,0,0,0,;13032,,,0,0,0,;130 …
```
=> fix parsing problems for hall of fame page with empty entries

src/gamestate/mod.rs, src/gamestate/social.rs
Soldier advice is used for the fortress attacks its the games advice of how many soldiers you should use when performing a fortress attack
=> otherplayer soldier advice

README.md, examples/expedition.rs, src/command.rs, src/error.rs, src/gamestate/character.rs, src/gamestate/dungeons.rs, src/gamestate/fortress.rs, src/gamestate/guild.rs, src/gamestate/items.rs, src/gamestate/mod.rs, src/gamestate/social.rs, src/gamestate/tavern.rs, src/gamestate/underworld.rs, src/lib.rs, src/misc.rs, src/session.rs, src/sso.rs
These typos were found by running following command:
```sh
codespell --write-changes --ignore-regex '\bcrate\b'
```
Afterwards I checked the changes that were made and removed some false
positives.
See: https://github.com/codespell-project/codespell
=> Fix typos in project

src/simulate/mod.rs
I think it's easy to verify, that class == Scout && class == Druid can not be true at the same time.
Edit: Assassin was missing entirely, I have added a commit for that aswell.
=> Fix druid not dodging & thus not activating bear form (also add assassin dodge chance)

src/gamestate/fortress.rs
Depending on the building type, a specific fortress level is required to be allowed to build it. The new helper function returns such fortress level.
=> Add function to determine required fortress level

src/gamestate/items.rs
I had the problem that an eternal life potion could not be parsed correctly. The reason for this was that `sub_ident` had the value 655360016. Since the value was greater than 16, it was incorrectly assumed that this is a resource. However, it could not be parsed as a resource either, since in this case the value can only be between 17 and 21. As a result, this particular eternal life potion was parsed as `ItemType::Unknown`.
This only happened with one eternal life potion, other ones were working fine. It is possible that this item is very old because this character exists for many years and I only recently started using it again. But I'm not sure when exactly this potion was bought.
=> Fix item parsing of raw type 12

src/gamestate/fortress.rs
In order to built/upgrade a building, different requirements have to be met. These depend on other buildings in the fortress. With the new helper function it can be checked if a particular building meets these requirements.
This pull request also fixes some lint issues in `required_min_fortress_level()`.
=> Add function to check if fortress building can be built 

src/gamestate/character.rs
It simply returns the cost of a mount. It can be used to check whether or not one has enough silver/mushrooms to buy it.
=> Add function to get cost of mount

src/command.rs, src/gamestate/guild.rs, src/gamestate/social.rs, src/gamestate/underworld.rs
To do so it was necessary to implement this trait for the enums and structs `Command` depends on as well.
This has been done to more effectively check for equality in unit tests. The macro `matches!()` for example is not able to check if the fields of the enum match as well.
Now the following is possible:
```rust
let command = Command::FortressBuild {
f_type: FortressBuildingType::Academy,
};
let building_type = FortressBuildingType::Academy;
assert_eq!(
command,
Command::FortressBuild {
f_type: building_type
}
);
```
=> Implement trait `PartialEq` for `Command`

src/gamestate/mod.rs
The are a fair number of `DateTime`s in this API where one wants to know if they are in the future or the past. This new function can be used to determine this. To check if the given `datetime` is in the present or the past, just negate the result.
=> Add function to check if a `DateTime` is in the future

src/gamestate/mod.rs
The "toilettfull" response is sent, even if the toilet is locked. A default toilet should therefore only be inserted if the toilet was actually used.
=> Fix incorrect toilet unlock status

src/command.rs, src/gamestate/fortress.rs
- Added a check in can_build() for character level >= 25 to be able to build/upgrade
- Added Fortress.in_use() which checks if a building is doing something preventing its upgrade
- Changed can_build() to check in_use() when determining whether building can be upgraded.
The character level check requires an extra argument for can_build(), which breaks compatibility. Is that an issue, or are there any workaround suggestions to preserve compatibility?
=> Added Fortress.in_use() and Building->Unit mapping, improved Fortress.can_build()

src/gamestate/mod.rs
Dungeon portal is automatically unlocked with level 99
=> fix dungeon portal not being unlocked correctly

src/gamestate/guild.rs
After you attack another guild there is a cool down for when you can start the next attack. This will now be parsed and exposed.
=> Parse next attack possible field

src/gamestate/mod.rs
The witch is automatically unlocked with level 66. No idea why some of my accounts got the witch data send before that but similar to how we handle other unlockables this simply set's it to `None` if we are below level 66.
=> Fix witch sometimes being set before actually being unlocked

.github/workflows/rust.yml, examples/expedition.rs, src/command.rs, src/error.rs, src/gamestate/character.rs, src/gamestate/fortress.rs, src/gamestate/mod.rs, src/gamestate/tavern.rs, src/misc.rs, src/response.rs
Also fixed all the formatting problems and clippy warnings that were already there. This should prevent any new problems from getting into the code base
=> Add simple CI workflows to check formatting and clippy warnings

src/command.rs, src/gamestate/fortress.rs
Yes the gather command looks a bit crazy, because it is. But I've double and triple checked it and it is actually correct.
Not sure how to feel about you technically being able to send a command like this
```rust
Command::FortressGatherSecretStorage { resource: FortressResourceType::Experience, amount: x }
```
which is wrong and won't work because there is no secret storage for experience only stone and wood.
But I think it's cleaner to use the enum values for stone and wood instead of using something like
```rust
Command::FortressGatherSecretStorage { collect_wood: true,  amount: x } // Collects wood
Command::FortressGatherSecretStorage { collect_wood: false, amount: x } // Collects stone
```
or an entirely new enum.
=> Add command and parsing for fortress secret storage

src/command.rs, src/gamestate/items.rs, src/gamestate/unlockables.rs
This is a breaking changes, but the previous method just did not work, so it should be good
TODO: I just tested this for one char and two items, but I need to make sure this is actually the correct approach for all characters
fixes #145
=> Parse enchantments into idents, that can be used to enchant items.

src/gamestate/items.rs
This allows direct comparisons between different potion sizes. For
example:
```
assert!(PotionSize::Large > PotionSize::Medium);
```
=> Implement trait `PartialOrd` for `PotionSize`

src/gamestate/arena.rs, src/gamestate/mod.rs, src/lib.rs
Winnerid sometimes contains a fightversion as well. Previous this was just returning an error. Now the value is correctly parsed and propagated to the fight rounds parsing. That method is still not actually using the version, but it could now.
Should fix #144
TODO: 
- Actually test, if this works
=> Correctly parse fightversion in winnerid

src/gamestate/fortress.rs
To finish the search in the gem mine, the found gem has to be collected using `Command::FortressGemStoneSearchFinish`. This means, as long as this command is not sent, the gem mine is still in use.
=> Fix check if gem mine is in use

src/command.rs, src/gamestate/mod.rs, src/gamestate/unlockables.rs
This pull request adds support for accessing and claiming yesterday's daily rewards of the Hellevator.
As a far as I can tell,  the S&F server only returns yesterday's daily rewards during login. This is unfortunate because it requires that the game state is updated manually.
Some of the logic was already implemented but commented out. I am unsure why this was done, as it seems to work fine.
=> Add support for yesterday's daily rewards of Hellevator

src/gamestate/mod.rs
This is a follow up of pull request https://github.com/the-marenga/sf-api/pull/153. It introduces a new technique to determine if yesterday's daily reward was claimed. I've tested it with multiple characters and it seems to be reliable.
=> Fix edge case of yesterday's daily reward of Hellevator

examples/dungeons.rs, src/gamestate/underworld.rs
The underworld resources souls & silver have been swapped originally. This has lead to underworld resources not being able to be collected properly (#165). The original issue mentioned upgrading the gold pit below lvl 25 having an influence, but tesing that with an upgrade from 14=>15, the original browser collect requests do not chance, the original order has just been wrong. Looking at all paths where the underworld resources have been used, no other places used the numeric values of the enum, or the order, so this should not break anything, except users, that manually cast them, which I do not really see happening
closes #165
=> Swap Underworld Resources Souls & Silver

Cargo.toml, src/misc.rs
aho-corasick is a pretty big dependency to only do a simple character replacement in two functions, so I rewrote it manually. It is now also a lot more readable/maintainable. No idea why I did it like that originally. I either wanted to be extra smart or completely misjudged the difficulty to do this in O(n). The only downside now is that the mapping is in two places, but I doubt that it will change, so it should not matter
=> Rewrote sf-string parsing. Removes aho-corasick and once_cell deps

src/gamestate/mod.rs, src/gamestate/tavern.rs, src/sso.rs
They retired the old system. Since you can now have N sacrifices, instead of just 1, there is now a `sacrifices_left`, which will replace used
=> Fix toilet used status

src/gamestate/mod.rs
Since the processing order of each response field isn't guaranteed, this can - sometimes -  cause parsed equipment items to be *lost*. This specifically happens if equipment items are parsed and set, **before** this code block runs.
Also affects `sf-scrapbook-helper` causing players to have 0 items.
=> Fix lost equipment
